import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("desktop README", () => {
  it("documents local sync queue and verification entrypoints", () => {
    const readmePath = resolve(
      dirname(fileURLToPath(import.meta.url)),
      "../README.md",
    );
    const readme = readFileSync(readmePath, "utf-8");

    expect(readme).toContain("Tauri 2 + Vue 3 + TypeScript");
    expect(readme).toContain("Pending sync");
    expect(readme).toContain("sync_state");
    expect(readme).toContain("sync_runs");
    expect(readme).toContain("task_sync_versions");
    expect(readme).toContain("getSyncState");
    expect(readme).toContain("saveSyncState");
    expect(readme).toContain("recordSyncRun");
    expect(readme).toContain("listRecentSyncRuns");
    expect(readme).toContain("baseVersion");
    expect(readme).toContain("buildDeltaPushFromPendingChanges");
    expect(readme).toContain("applyDeltaPushResponse");
    expect(readme).toContain("applyDeltaPullResponse");
    expect(readme).toContain("applyRemoteTask");
    expect(readme).toContain("deleteRemoteTask");
    expect(readme).toContain("without writing `local_changes`");
    expect(readme).toContain("runLocalSyncSimulation");
    expect(readme).toContain("createLocalSyncRunner");
    expect(readme).toContain("default Settings route");
    expect(readme).toContain("in-memory transport");
    expect(readme).toContain("createSyncRunner");
    expect(readme).toContain("createHttpLikeSyncTransport");
    expect(readme).toContain("HTTP-like sync transport");
    expect(readme).toContain("createHttpSyncTransport");
    expect(readme).toContain("injected `fetch`");
    expect(readme).toContain("headers provider");
    expect(readme).toContain("baseUrl is not configured");
    expect(readme).toContain("createRemoteSyncConfig");
    expect(readme).toContain("createRemoteSyncRunner");
    expect(readme).toContain("remote sync runner factory");
    expect(readme).toContain("runner: null");
    expect(readme).toContain("createDefaultSettingsSyncRuntime");
    expect(readme).toContain("default settings sync runtime");
    expect(readme).toContain("VITE_MOMO_SYNC_BASE_URL");
    expect(readme).toContain("VITE_MOMO_SYNC_TOKEN");
    expect(readme).toContain("default `/settings` route reads");
    expect(readme).toContain("route/status");
    expect(readme).toContain("runOnce");
    expect(readme).toContain("runs delta pull after delta push");
    expect(readme).toContain("sinceCursor");
    expect(readme).toContain("transport");
    expect(readme).toContain("clears last error");
    expect(readme).toContain("records last error");
    expect(readme).toContain("pendingConflictCount");
    expect(readme).toContain("SYNC_RUN_STATUSES");
    expect(readme).toContain("summarizeDeltaPushResponse");
    expect(readme).toContain("Already synced");
    expect(readme).toContain("summarizePendingConflicts");
    expect(readme).toContain("summarizePendingConflictDetails()");
    expect(readme).toContain("Sync conflicts");
    expect(readme).toContain("Sync conflicts can show matching pending change action, entity, createdAt, and payload summary");
    expect(readme).toContain("Sync status");
    expect(readme).toContain("Sync rejections");
    expect(readme).toContain("Rejected changes are read-only");
    expect(readme).toContain("summarizeRejectedChanges()");
    expect(readme).toContain("Sync rejections can show matching pending change action, entity, and payload summary");
    expect(readme).toContain("Pull applied");
    expect(readme).toContain("Sync state");
    expect(readme).toContain("Pending changes");
    expect(readme).toContain("summarizePendingLocalChanges()");
    expect(readme).toContain("Pending changes load errors do not hide Local database, Sync state, or Sync history");
    expect(readme).toContain("Sync history");
    expect(readme).toContain("listRecentSyncRuns(3)");
    expect(readme).toContain("Sync history load errors do not hide Local database or Sync state");
    expect(readme).toContain("Remote sync config");
    expect(readme).toContain("Sync action");
    expect(readme).toContain("Local simulation");
    expect(readme).toContain("onRunLocalSyncSimulation");
    expect(readme).toContain("Local sync simulation");
    expect(readme).toContain("keyboard-accessible");
    expect(readme).toContain("sync runner boundary");
    expect(readme).toContain("sync run history");
    expect(readme).toContain("cursor state boundary");
    expect(readme).toContain("local simulation entrypoint");
    expect(readme).toContain("Manual acceptance");
    expect(readme).toContain("http://localhost:1420/settings");
    expect(readme).toContain("Remote config display smoke");
    expect(readme).toContain("VITE_MOMO_SYNC_BASE_URL=https://api.example.test/momo");
    expect(readme).toContain("VITE_MOMO_SYNC_TOKEN=local-dev-token");
    expect(readme).toContain("confirm `Remote sync config` shows `enabled`");
    expect(readme).toContain("confirm `Sync action` remains `Local simulation`");
    expect(readme).toContain("default button still uses local simulation");
    expect(readme).toContain("click `Local sync simulation`");
    expect(readme).toContain("confirm `Sync status`");
    expect(readme).toContain("confirm `Pull applied`");
    expect(readme).toContain("confirm `Sync state`");
    expect(readme).toContain("refreshes `Sync state`");
    expect(readme).toContain("sync errors refresh `Sync state`");
    expect(readme).toContain("does not hide the original sync error");
    expect(readme).toContain("Vite smoke only verifies the route, button, and error handling");
    expect(readme).toContain("Full SQLite success flow requires `npm run tauri dev`");
    expect(readme).toContain("no real network");
    expect(readme).toContain("BE-03 local sync boundary");
    expect(readme).toContain("local BE-03 boundary is complete enough for desktop-only validation");
    expect(readme).toContain("Next roadmap boundary");
    expect(readme).toContain("BE-04 realtime events");
    expect(readme).toContain("BE-01 / IF-01 production backend prerequisites");
    expect(readme).toContain("keep the default Settings route on local simulation");
    expect(readme).not.toContain("下一步建议围绕 HTTP transport 增加认证 header / base URL 配置边界");
    expect(readme).toContain("npm run verify");
  });
});
